-- The file manager (dir.lua), on the harness: `-` lists the file's
-- directory, `-` again its parent, `~` moves the working directory
-- there (oil's), again from a listing opened by name; and `_` (the
-- working directory's listing, from anywhere).
local dir = os.tmpname()
os.remove(dir)
dir = dir .. "-dash"
local inner = kawoosh.fs.join(dir, "inner")
kawoosh.fs.create(inner, true)
kawoosh.fs.write(kawoosh.fs.join(inner, "f.txt"), "x")

kawoosh.cmd("e " .. kawoosh.fs.join(inner, "f.txt"))
kawoosh.frame()
kawoosh.press("-")
kawoosh.frame()
kawoosh.test.eq(kawoosh.buf.name(), "dir: " .. inner)
kawoosh.test.eq(kawoosh.buf.line(1), "../")
kawoosh.test.eq(kawoosh.buf.line(2), "f.txt")
kawoosh.press("-")
kawoosh.frame()
kawoosh.test.has(kawoosh.buf.lines(), "inner/", "the parent's listing")
kawoosh.press("~")
kawoosh.frame()
kawoosh.cmd("pwd")
kawoosh.frame()
kawoosh.test.eq(kawoosh.message(), dir, "the working directory moved")

kawoosh.cmd("dir " .. inner)
kawoosh.frame()
kawoosh.press("~")
kawoosh.frame()
kawoosh.cmd("pwd")
kawoosh.frame()
kawoosh.test.eq(kawoosh.message(), inner, "`~` is `dir cd`")
kawoosh.cmd("e " .. kawoosh.fs.join(inner, "f.txt"))
kawoosh.frame()
kawoosh.cmd("cd " .. dir)
kawoosh.frame()
kawoosh.press("_")
kawoosh.frame()
kawoosh.test.eq(kawoosh.buf.name(), "dir: " .. dir, "`_` lists the working directory")
kawoosh.fs.remove(dir)
