[package]
name = "kawoosh"
publish.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
log.workspace = true
env_logger.workspace = true
gpui.workspace = true
gpui_platform.workspace = true
rust-embed.workspace = true
anyhow.workspace = true
