[workspace]
resolver = "3"
members = ["core", "kawoosh", "systems", "term", "text-buffer", "ui"]

[workspace.package]
publish = false
version = "0.0.1"
edition = "2024"
authors = ["Nasonov Viktor <me@qxuken.dev>"]
repository = "https://drydock9.qxuken.dev/qxuken/kawoosh"

[workspace.dependencies]
text-buffer = { path = "./text-buffer" }
kawoosh-core = { path = "./core" }

log = { version = "0.4.33", features = ["serde"] }
env_logger = "0.11.11"

kawoosh-ui = { path = "./ui" }
kawoosh-term = { path = "./term" }
kawoosh-systems = { path = "./systems" }

sdl3 = "0.18"
cosmic-text = "0.19"
alacritty_terminal = "0.26"
portable-pty = "0.9"
crossbeam-channel = "0.5"
tree-sitter = "0.26"
tree-sitter-rust = "0.24"
lsp-types = "0.97"
mlua = { version = "0.12", features = ["luajit", "vendored"] }
rusqlite = { version = "0.40", features = ["bundled"] }
serde_json = "1"

anyhow = { version = "1.0.104", features = ["backtrace"] }
mimalloc = "0.1.52"
smallvec = { version = "1.15.2", features = ["serde"] }
serde = { version = "1.0.229", features = ["derive"] }
schemars = "1.2.1"
slotmap = { version = "1.1.1", features = ["serde"] }

criterion = "0.8.2"

bitflags = { version = "2.13.1", features = ["serde"] }
derive_more = { version = "2.1.1", features = ["as_ref", "deref", "deref_mut"] }
