[workspace]
resolver = "3"
members = ["kawoosh", "resources", "text-buffer"]

[workspace.package]
publish = false
version = "2026.6.0"
edition = "2024"
authors = ["Nasonov Viktor <me@qxuken.dev>"]
repository = "https://drydock9.qxuken.dev/qxuken/kawoosh"

[workspace.dependencies]
text-buffer = { path = "./text-buffer" }
resources = { path = "./resources" }

log = "0.4.33"
env_logger = "0.11.11"

gpui = { git = "https://drydock9.qxuken.dev/mirrors/zed.git", rev = "65e1c5af258d4c80036467d583691f3f9ded0897" }
gpui_platform = { git = "https://drydock9.qxuken.dev/mirrors/zed.git", rev = "65e1c5af258d4c80036467d583691f3f9ded0897", features = [
    "font-kit",
    "wayland",
    "x11",
] }
anyhow = { version = "1.0.103", features = ["backtrace"] }
rust-embed = { version = "8.12.0", features = [
    # "compression",
    "include-exclude",
] }
mimalloc = "0.1.52"
smallvec = "1.15.2"
