[package]
name = "kawoosh-lua"
publish.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
kawoosh-doc.workspace = true
kawoosh-editor.workspace = true
kui-lua.workspace = true
kui-core.workspace = true
mlua.workspace = true
slotmap.workspace = true
log.workspace = true
