[package]
name = "text-buffer"
publish.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
derive_more.workspace = true
memchr = "2"
memmap2 = "0.9"

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "insert"
harness = false
