[package]
name = "kawoosh-doc"
publish.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
text-buffer.workspace = true
slotmap.workspace = true
unicode-segmentation.workspace = true
imara-diff = "0.2"
