[package]
name = "kawoosh-editor"
publish.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
kawoosh-doc.workspace = true
slotmap.workspace = true
regex = "1"
globset = "0.4"
memchr = "2"
text-buffer.workspace = true
