[package]
name = "kawoosh-systems"
publish.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
kawoosh-doc.workspace = true
text-buffer.workspace = true
memmap2 = "0.9"
crossbeam-channel.workspace = true
log.workspace = true
anyhow.workspace = true
serde_json.workspace = true
serde.workspace = true
kawoosh-languages.workspace = true
tree-sitter.workspace = true
rusqlite.workspace = true
ignore = "0.4"
